# Generated by BoostInstall.cmake for boost_coroutine2-1.77.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.77.0 EXACT)
find_dependency(boost_config 1.77.0 EXACT)
find_dependency(boost_context 1.77.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_coroutine2-targets.cmake")
