# Generated by BoostInstall.cmake for boost_range-1.77.0

include(CMakeFindDependencyMacro)

find_dependency(boost_array 1.77.0 EXACT)
find_dependency(boost_assert 1.77.0 EXACT)
find_dependency(boost_concept_check 1.77.0 EXACT)
find_dependency(boost_config 1.77.0 EXACT)
find_dependency(boost_container_hash 1.77.0 EXACT)
find_dependency(boost_conversion 1.77.0 EXACT)
find_dependency(boost_core 1.77.0 EXACT)
find_dependency(boost_detail 1.77.0 EXACT)
find_dependency(boost_iterator 1.77.0 EXACT)
find_dependency(boost_mpl 1.77.0 EXACT)
find_dependency(boost_optional 1.77.0 EXACT)
find_dependency(boost_preprocessor 1.77.0 EXACT)
find_dependency(boost_regex 1.77.0 EXACT)
find_dependency(boost_static_assert 1.77.0 EXACT)
find_dependency(boost_tuple 1.77.0 EXACT)
find_dependency(boost_type_traits 1.77.0 EXACT)
find_dependency(boost_utility 1.77.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_range-targets.cmake")
