# Generated by BoostInstall.cmake for boost_python-1.77.0

include(CMakeFindDependencyMacro)

find_dependency(boost_python38 1.77.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_python-targets.cmake")
