# Generated by BoostInstall.cmake for boost_crc-1.77.0

include(CMakeFindDependencyMacro)

find_dependency(boost_array 1.77.0 EXACT)
find_dependency(boost_config 1.77.0 EXACT)
find_dependency(boost_integer 1.77.0 EXACT)
find_dependency(boost_type_traits 1.77.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_crc-targets.cmake")
