# Generated by BoostInstall.cmake for boost_fiber_numa-1.77.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.77.0 EXACT)
find_dependency(boost_config 1.77.0 EXACT)
find_dependency(boost_context 1.77.0 EXACT)
find_dependency(boost_fiber 1.77.0 EXACT)
find_dependency(boost_smart_ptr 1.77.0 EXACT)
find_dependency(boost_algorithm 1.77.0 EXACT)
find_dependency(boost_filesystem 1.77.0 EXACT)
find_dependency(boost_format 1.77.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_fiber_numa-targets.cmake")
