# Generated by BoostInstall.cmake for boost_atomic-1.77.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.77.0 EXACT)
find_dependency(boost_config 1.77.0 EXACT)
find_dependency(boost_static_assert 1.77.0 EXACT)
find_dependency(boost_type_traits 1.77.0 EXACT)
find_dependency(boost_winapi 1.77.0 EXACT)
find_dependency(boost_align 1.77.0 EXACT)
find_dependency(boost_predef 1.77.0 EXACT)
find_dependency(boost_preprocessor 1.77.0 EXACT)
set(THREADS_PREFER_PTHREAD_FLAG ON)
find_dependency(Threads)

include("${CMAKE_CURRENT_LIST_DIR}/boost_atomic-targets.cmake")
