# Generated by BoostInstall.cmake for boost_regex-1.77.0

include(CMakeFindDependencyMacro)

find_dependency(boost_config 1.77.0 EXACT)
find_dependency(boost_throw_exception 1.77.0 EXACT)
find_dependency(boost_predef 1.77.0 EXACT)
find_dependency(boost_assert 1.77.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_regex-targets.cmake")
