# Generated by BoostInstall.cmake for boost_multiprecision-1.77.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.77.0 EXACT)
find_dependency(boost_config 1.77.0 EXACT)
find_dependency(boost_core 1.77.0 EXACT)
find_dependency(boost_integer 1.77.0 EXACT)
find_dependency(boost_lexical_cast 1.77.0 EXACT)
find_dependency(boost_math 1.77.0 EXACT)
find_dependency(boost_predef 1.77.0 EXACT)
find_dependency(boost_random 1.77.0 EXACT)
find_dependency(boost_rational 1.77.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_multiprecision-targets.cmake")
