# Generated by BoostInstall.cmake for boost_function-1.77.0

include(CMakeFindDependencyMacro)

find_dependency(boost_assert 1.77.0 EXACT)
find_dependency(boost_bind 1.77.0 EXACT)
find_dependency(boost_config 1.77.0 EXACT)
find_dependency(boost_core 1.77.0 EXACT)
find_dependency(boost_integer 1.77.0 EXACT)
find_dependency(boost_preprocessor 1.77.0 EXACT)
find_dependency(boost_throw_exception 1.77.0 EXACT)
find_dependency(boost_type_index 1.77.0 EXACT)
find_dependency(boost_type_traits 1.77.0 EXACT)
find_dependency(boost_typeof 1.77.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_function-targets.cmake")
