# Generated by BoostInstall.cmake for boost_json-1.77.0

include(CMakeFindDependencyMacro)

find_dependency(boost_align 1.77.0 EXACT)
find_dependency(boost_assert 1.77.0 EXACT)
find_dependency(boost_config 1.77.0 EXACT)
find_dependency(boost_container 1.77.0 EXACT)
find_dependency(boost_exception 1.77.0 EXACT)
find_dependency(boost_mp11 1.77.0 EXACT)
find_dependency(boost_system 1.77.0 EXACT)
find_dependency(boost_throw_exception 1.77.0 EXACT)
find_dependency(boost_utility 1.77.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_json-targets.cmake")
